name: up_the_shelf
description: Flutter take home project for App and Up.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  google_sign_in: ^5.3.0
  provider: ^6.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  responsive_framework: ^0.1.7
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/uptheshelf-logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
